name: Validate Files
on: workflow_dispatch
jobs:
  validate:
    runs-on: windows-latest
    steps:
      - name: Get repo code on react
        uses: actions/checkout@v3
      - name: validate html file
        run: test -f index.html
      - name: validate js file
        run: test -f script.js
      - name: validate js code
        run: node --check script.js
